### ISSUE TITLE
Review needed on article on color topics for programmers

### ISSUE THREAD

**Issue by peteroupc** [peteroupc/peteroupc.github.io#2]
On peteroupc.github.io, I've added an [article](http://peteroupc.github.io/colorgen.html) bringing together many color topics of general interest to programmers and offering solutions and pseudocode.  I encourage anyone to review and comment on this article, especially @KelSolaar , who appears to have a lot of color knowledge, and to pass this message on to other willing reviewers.  In particular, this document discusses--

- popular formats for red-green-blue (RGB) colors,
- several color models of practical interest, including conversion methods,
- how to generate colors with certain properties,
- color differences,
- color mixing,
- color maps,
- how to find the dominant colors of an image, and
- colors as spectral functions.

**Comment by thomasmansencal** [comment]
Hey @peteroupc,

Went through the page quickly, good stuff overall! I will have to do a thorough re-read but I spotted a few things:

- `as the YCbCrToRgb709 and RgbToCbCr709 methods` has a typo at `RgbToCbCr709`.
-  The section regarding [sRGB](http://peteroupc.github.io/colorgen.html#sRGB_and_Linearized_RGB) should probably introduce some terminology regarding RGB colourspace transfer functions. We have written an article that could be useful in that regard: http://colour-science.org/posts/the-importance-of-terminology-and-srgb-uncertainty/
- `Colors can also be represented as functions that describe a color sensation at each wavelength of the visible spectrum.` This description disturbs me and might need to be reformulated, e.g. talking about varying quantity of electro-magnetic radiation at each wavelength.
- `The light received by the object is called an illuminant`. This is not quite correct, light received by an object is "simply" incident radiation, either emitted by a light source or being reflected by surrounding surfaces. A light source is an object that emits light, an illuminant is a reproducible light source standard by the CIE and usually mathematically/analitically modelled. I like to think that all illuminants are light sources but not all light sources are illuminants.

Cheers,

Thomas

**Comment by thomasmansencal** [comment]
By the way something worth linking and looking at whenever you want an exact definition on colour science terms: http://eilv.cie.co.at/

**Comment by peteroupc** [comment]
@ellelstone : Would you mind reviewing [this article of mine](http://peteroupc.github.io/colorgen.html) on common color topics for programmers?  I've just updated the document to better clarify ICC profile contexts after reading some of your blog posts.  (See the commit history for details.)

Moreover, there are some issues. 

- In ICC version 4 profiles, there is an additional complication because in such profiles, RGB values encoded in the Profile Connection Space must not have been black-normalized, that is, they can be darker than the sRGB "black point" (in comparison, black-normalization was allowed in version 2 profiles, so that (0, 0, 0) meant the sRGB black point).  However, your [article](https://ninedegreesbelow.com/photography/srgb-color-space-to-profile.html) on creating certain ICC profiles doesn't go into "black points", veiling glare, or preparing v4 profiles at all.  Is this requirement important enough in practice (especially with respect to how XYZ colors are to be interpreted) that my article should comment on it somewhere?
- When converting from RGB to XYZ (with the "relative XYZ" convention as I define it in the document), does an XYZ color with Y = 0 usually mean the RGB color space's "black point" (very small positive absolute luminance) or "absolute black" (with 0 cd/m<sup>2</sup> absolute luminance)?

**Comment by ellelstone** [comment]
On 09/01/2017 06:33 PM, Peter Occil wrote:
> @ellelstone : Would you mind reviewing [this article of mine](http://peteroupc.github.io/colorgen.html) on common color topics for programmers?  I've just updated the document to better clarify ICC profile contexts after reading some of your blog posts.  (See the commit history for details.)

Hi Peter,

My apologies, I don't have the time and energy to do an adequate review. 
If you make a post to the pixls.us discussion forum, there are quite a 
few developers of image-editing software who will see your post and 
perhaps chime in (you can direct a comment/question specifically to me 
using "@elle"):

https://discuss.pixls.us/

You mentioned my website, so if you didn't already see this article you 
might find it helpful:

Completely Painless Programmer's Guide to XYZ, RGB, ICC, xyY, and TRCs
https://ninedegreesbelow.com/photography/xyz-rgb.html

> Moreover, there are some issues.
> 
> - In ICC version 4 profiles, there is an additional complication because in such profiles, RGB values encoded in the Profile Connection Space must not have been black-normalized, that is, they can be darker than the sRGB "black point" (in comparison, black-normalization was allowed in version 2 profiles, so that (0, 0, 0) meant the sRGB black point).  However, your [article](https://ninedegreesbelow.com/photography/srgb-color-space-to-profile.html) on creating certain ICC profiles doesn't go into "black points", veiling glare, or preparing v4 profiles at all.  Is this requirement important enough in practice (especially with respect to how XYZ colors are to be interpreted) that my article should comment on it somewhere?

My apologies, I'm not sure what you mean by 'RGB values encoded in the 
Profile Connection Space must not have been black-normalized, that is, 
they can be darker than the sRGB "black point"'. I think you might be 
referring to the ICC's V4 "reference medium black point" (D.2.2 PCS for 
perceptual rendering, 
http://color.org/specification/ICC1v43_2010-12.pdf), which is non-zero 
and a change from the V2 specs.

The ICC V4 reference medium with its nonzero black point is used in a 
print-oriented workflow described by the ICC on the color.org website, 
but not everyone who makes prints actually uses this specific workflow.

Of course veiling glare and device black points are important 
considerations. But the XYZ color space itself has a zero black point - 
how would you specify a non-zero black point if you didn't have a 
reference color space that supplied an actual zero black point?

The color.org website does supply various new versions of selected old 
(sRGB and other) profiles, that in my opinion shouldn't be used without 
carefully considering whether one's workflow is actually the type of 
workflow for which the new versions were designed. The intended workflow 
is well-documented on the color.org website, but from various forum 
comments I suspect a lot of people try to use these new color.org 
profiles without reading the documentation.

The really interesting innovations in ICC profiles are in the 
up-and-coming V5/iccMAX:
http://color.org/iccmax/index.xalter

> - When converting from RGB to XYZ (with the "relative XYZ" convention as I define it in the document), does an XYZ color with Y = 0 usually mean the RGB color space's "black point" (very small positive absolute luminance) or "absolute black" (with 0 cd/m<sup>2</sup> absolute luminance)?
> 

Y=0 means "absolute black".

My apologies again, I'm not sure what you mean by 'the RGB color space's 
"black point" (very small positive absolute luminance)'. There are many 
RGB color spaces:

For *device* color spaces (which might or might not be RGB color 
spaces), the measured black point will vary from device to device, and 
will also vary depending on how the measuring is done and on what kind 
of profile is being made. Even though "Y=0" isn't an attainable black 
point for imaging devices, sometimes the device profile black point is 
still set to Y=0, an example being the very commonly used linear gamma 
matrix camera input profiles. For various good and sufficient reasons 
even many monitor ICC profiles have a zero black point.

My ICC RGB *working space* profiles all have a zero black point:

Elle Stone's Well-Behaved ICC Profiles and Code
https://ninedegreesbelow.com/photography/lcms-make-icc-profiles.html

https://github.com/ellelstone/elles_icc_profiles

I've never seen an actual RGB matrix working space profile with a 
non-zero black point - is anyone distributing RGB matrix/working space 
profiles with non-zero black points?

Best,
Elle
-- 
http://ninedegreesbelow.com
Color management and free/libre photography

**Comment by peteroupc** [comment]
Let me clarify some points.

> My apologies, I'm not sure what you mean by 'RGB values encoded in the Profile Connection Space must not have been black-normalized, that is, they can be darker than the sRGB "black point"'.

XYZ is nominally specified such that Y is in candelas per meter squared (cd/m^2) ("absolute XYZ").  In practice, however, XYZ is often normalized to a specific white point and "black point" (ranging from 0 to some known value -- "relative XYZ", or if it helps understanding, "relative colorimetric with black point compensation"), each of which can have different absolute XYZ values, so that, in a hypothetical RGB color space for the sake of discussion and example, Y can range from 0 to 1, where Y = 0 is the RGB color space's black point (with an absolute Y [luminance] of 0.5 cd/m^2), and Y = 1 is the white point (whith an absolute Y of 100 cd/m^2).  However, not just in ICC V4 profiles but perhaps in non-ICC contexts, XYZ can also be normalized to a specific white point and "absolute black" (where "absolute black" means an absolute Y of 0 cd/m^2), so that, in the same hypothetical RGB color space, Y = 0 has a luminance (absolute Y) of 0 cd/m^2, regardless of what the RGB color space defines as black (i.e., even if "absolute black" is outside the gamut of the RGB color space -- "relative colorimetric without black point compensation").

Hence my confusion -- there are two plausible "relative XYZ" conventions in play.

> My apologies again, I'm not sure what you mean by 'the RGB color space's "black point" (very small positive absolute luminance)'. There are many RGB color spaces:

When I said "sRGB black point", I was referring to the "veiling glare luminance" ("black point" luminance) 0.2 cd/m^2.  Is is true that the "sRGB black point" (what sRGB defines as black) has a luminance of 0.2 cd/m^2 (absolute Y = 0.2) rather than 0 cd/m^2 (absolute Y = 0, the start of the absolute XYZ scale)?

**Comment by ellelstone** [comment]
Hmm, there is always something else to learn about color management and color science. I've never heard anyone talk about relative and absolute XYZ. Your phrase "absolute zero" took me by surprise, but I ignored it, assuming that "Y=0" means "no light is emitted/reflected towards the viewer", whether measured on an absolute or relative scale. 

So if there is such a thing as "absolute" and "relative" XYZ, then I need to do some reading and figure out what these things might be. I always assumed that "Y=1" (or 100, or whatever value might be convenient for whatever purpose) was relative luminance, not absolute luminance.

The original (V2) sRGB ICC profile is a matrix profile (XYZ connection space), with a zero black point:

      <TagSignature>bkpt</TagSignature>
      <XYZNumber X="0.00000000" Y="0.00000000" Z="0.00000000"/>

The above tag is from sRGB.icm distributed by ArgyllCMS - it's in the "ref" folder.

It seems that every time I look at the color.org website there is a new set of sRGB profiles available, and older ones have disappeared and/or been renamed. One of the current versions - sRGB2014.icc - is a matrix profile with a non-zero black point tag:

      <TagSignature>bkpt</TagSignature>
      <XYZNumber X="0.00241089" Y="0.00250244" Z="0.00205994"/>

But the TRC tags start at zero, exactly the sae as the original V2 sRGB profile:    <curveType>
      <TagSignature>bTRC</TagSignature>
      <TagSignature>gTRC</TagSignature>
      <TagSignature>rTRC</TagSignature>
      <Curve>
           0     5    10    15    20    25    30    35    40    45    50    55 . . . 

I don't understand how the V4 specs allow making a matrix profile with TRC tags that starts at 0, but with a non-zero black point. Perhaps you can explain this? I don't have a clue what this non-zero black point tag might be used for.

Various other versions of the V4 sRGB profile available from color.org are LUT profiles (not matrix profiles) using the LAB connection space. You can download the color.org sRGB profiles here - it's a good idea to read the linked-to documentation for each profile: http://www.color.org/srgbprofiles.xalter

0.2cd/m^2 refers to the black point of the V4 reference medium, which is not the same as the sRGB ICC profile itself:
http://www.color.org/chardata/rgb/srgb.xalter

**Comment by ellelstone** [comment]
Hmm, after pondering what you've said about using and not using black point compensation, I think I see what you are trying to say. But somewhere there is a conceptual confusion. 

Try this as an alternative description, confining the discussion to relative colorimetric conversions between RGB ICC profile color spaces, using and not using black point compensation:

1. XYZ is the reference color space.

2. RGB ICC profiles describe variously-sized and -shaped color gamuts located in XYZ.

3. Conversions between RGB ICC profiles use XYZ as the Profile Connection Space.

4. "Relative colorimetric intent with and without black point compensation" refers to converting an image from one RGB ICC profile to another RGB ICC profile. It doesn't refer to converting from RGB to XYZ.

So as an example, RGB profile A might have a zero black point, and RGB profile B might have a higher-than-zero black point. Let's also assume (to eliminate complications) that RGB profile B's color gamut is entirely contained within RGB profile A's color gamut.

In both RGB color spaces the black point is R=G=B=0. But R=G=B=0 doesn't point to the same place in XYZ for profile A as it does for profile B:

* For profile A (which has a zero black point), R=G=B=0 converts to X=Y=Z=0.

* For profile B (which has a higher-than-zero black point), R=G=B=0 converts to XYZ values where Y>0.

So if you have an image in the profile B color space, for which all the pixels have the RGB values R=G=B=0, and you convert to profile A *not* using black point compensation, then you'll get some different, greater than zero RGB values after converting to profile A. 

But the XYZ values for the image will remain the same before and after converting from B to A.

Things change if you convert from B to A, and *do* use black point compensation, but I'll let you work out what will happen.

It's worthwhile finding some example V2 profiles (V2, because LCMS2 can handle V2 profiles, but ArgyllCMS can't handle V4 profiles), with and without non-zero black points, and then spending some time with ArgyllCMS xicclu, and LCMS2 transicc, converting back and forth between RGB and XYZ and also between the two profiles. For transicc you can experiment with using and not using black point compensation. For xicclu, there isn't an option to use black point compensation.

**Comment by peteroupc** [comment]
For context:  My confusion arose after reading the following document on preparing ICC profiles (especially sections A.5, A.6, and B.1):

https://www.w3.org/Graphics/Color/srgb

**Comment by ellelstone** [comment]
> For context: My confusion arose after reading the following document on preparing ICC profiles (especially sections A.5, A.6, and B.1): https://www.w3.org/Graphics/Color/srgb

Well, that really is a confusing document! It does indeed talk about absolute XYZ. It also very clearly specifies that it's a modification of the original sRGB specs.

I encourage you to carefully compare these two documents:
https://www.w3.org/Graphics/Color/sRGB
https://www.w3.org/Graphics/Color/srgb

The above addresses seem to only differ in having uppercase "RGB" for the second document. But actually the extensions are missing. Here are the full urls:
https://www.w3.org/Graphics/Color/sRGB.html (original sRGB specs)
https://www.w3.org/Graphics/Color/srgb.pdf (sRGB specs reinterpreted)

You might also want to look at these two documents:
https://webstore.iec.ch/publication/6168 [Editor's note: Edited link to point to official specification.]
http://web.archive.org/web/20030212204955/http://www.srgb.com/basicsofsrgb.htm

My apologies in advance if below I'm explaining stuff you already know. Most of the time when people talk about XYZ, they are talking about relative XYZ values, so the Y of XYZ is relative luminance. It will help to have some preliminary definitions:

* Lambertian reflector: 
https://en.wikipedia.org/wiki/Lambertian_reflectance
* (absolute) Luminance (cd/m^2): 
https://en.wikipedia.org/wiki/Luminance
* Relative luminance: 
https://en.wikipedia.org/wiki/Relative_luminance

Let's assume that relative Y (relative luminance) of XYZ is scaled from 0.0 to 1.0 (which is the usual case), and can go higher than 1.0 in the case of specular reflections.

Also assume the following hypothetical perfect scene:

1. A perfectly absorbing surface (a "black hole"), 0% of the light striking the surface is reflected.
2. A perfect Lambertian reflector (100% of the light striking the surface is diffusely reflected).
3. A bunch of perfectly diffusely reflecting gray objects that reflect somewhere between 0 and 100% of the light that falls on them. Let's say one such object reflects 0.184187% of the light falling on it (middle gray), and another reflects 0.025% of the light falling on it (veiling glare assumed in https://www.w3.org/Graphics/Color/srgb.pdf).
4. A light source outside the scene, and assume none of the objects in the scene are in a shadow cast by some other object.
5. No specular reflections anywhere in the scene.

Here are the relative Y values of the objects in the scene:

Perfect Lambertian reflector: Y=1.0. 
Gray object reflecting 184187% of the light: Y= 0.184187.
Gray object reflecting 0.025% of the light: Y=0.025.
"Black hole": Y=0.0.

If one is given the absolute luminance of the light reflecting off the perfect Lambertian reflector, one can use the scene relative luminance values to calculate scene absolute luminance values.  So if the absolute luminance of the light coming from the Lambertian reflector is 80cd/m^2 (to match the value given in the spec, but of course in the spec the light is emitted by the monitor rather than reflected by an object illuminated by a separate light source), then if one wants to speak in terms of absolute XYZ, here are the absolute Y values:

Perfect Lambertian reflector: 
ab_Y = 1.0 times 80 cd/m^2 = 80 cd/m^2. 

Gray object reflecting 0.184187% of the light (middle gray): 
ab_Y = 0.184187 times 80 cd/m^2 = 14.735 cd/m^2.

Gray object reflecting 0.025% of the light (assumed veiling glare): 
ab_Y = 0.025 times 80cd/m^2 = 2 cd/m^2.

"Black hole": 
ab_Y = 0.0 times 80 cd/m^2 = 0 cd/m^2.

OK, that takes care of the absolute Y values in the revised spec. What about X and Z? This requires knowing the color of the light. For the sRGB color space, the color of the light is the D65 values given by the sRGB color space spec white point xy values. These values are used when making an sRGB ICC profile from the sRGB color space specs (https://ninedegreesbelow.com/photography/srgb-color-space-to-profile.html). 

You can get the corresponding XYZ values for sRGB D65 color profile input from ArgyllCMS xicclu as follows:

xicclu -ia sRGB-elle-V2-g10.icc
1.000000 1.000000 1.000000 [RGB] -> 0.950455 1.000000 1.089050 [XYZ]
0.184187 0.184187 0.184187 [RGB] -> 0.175061 0.184187 0.200589 [XYZ]
0.025000 0.025000 0.025000 [RGB] -> 0.023761 0.025000 0.027226 [XYZ]
0.000000 0.000000 0.000000 [RGB] -> 0.000000 0.000000 0.000000 [XYZ]

Notice these are relative XYZ values, which is the way XYZ values are usually expressed. To get from relative sRGB XYZ values to the absolute XYZ values given in https://www.w3.org/Graphics/Color/srgb.pdf, just multiply all the XYZ values by the absolute luminance of the Lambertian reflector, which we've assumed (just to fit the revised spec!) is 80 cd/m^2:

Lambertian reflector:                                     76.03640 80.00000 87.12400
Middle gray (18% XYZ gray=50% LAB gray): 14.00488 14.73496 16.04712
0.025 "nearly black":                                         1.90088  2.00000  2.17808
"Black hole":                                                      0.00000  0.00000  0.00000

Pulling out the absolute XYZ values used in the "6. Tristimulus value normalization" equations:
4.Reference display white point luminance:   76.03640 80.00000 87.12400
5.Reference veiling glare luminance:               1.90088   2.00000   2.17808

Some points:

First, thank you! for pointing me to the "revised spec" document posted on the w3 website. I did find another reference to absolute XYZ, in this book: Color and Mastering for Digital Cinema, by Glenn Kennel, which talks about absolute XYZ in the context of setting up projectors.

Second, as far as I know, nobody has used the "revised spec" to make sRGB ICC profiles for use with free/libre imaging software or to code up internal sRGB transforms between sRGB and XYZ.

Third, if editing software tried to use this revised sRGB spec with its "normalized tristimulus values" for actual editing algorithms, then just looking the equation in "7. Conversion from XYZ (D65) to linear sRGB values" (which uses the values calculated in "6. Tristimulus value normalization"), I *think* that various editing results would produce odd offsets. But I'm not enough of a matrix math whiz to "know just by looking" what would happen, and I'm not interested enough to take the required time to set up the equations to verify what would happen. If someone else wants to check into this, I'd be interested in the results.

Fourth, you have to ask yourself what the intended context - the use case - for the revised sRGB spec really is. I'm not sure, but I think maybe the context is using sRGB as a monitor profile. Perhaps related, color.org used to supply an odd sRGB profile that was intended to be used as a monitor profile - See https://ninedegreesbelow.com/photography/srgb-profile-comparison.html#blackpoint - and here's a link to the "no black scaling" profile in question: http://www.color.org/black_scaled_2009_srgb.xalter

Fifth: If the revised spec is for use as a monitor profile, how many monitors actually are calibrated to have a D65 white point with a luminance of 80cd/m^2? Mine is calibrated to something like D60 and 64cd/m^2 - many people recommend 100cd/m^2 for image editing, but I find that a bit bright.

Sixth: The "revised sRGB spec" defines "veiling glare" as "reference viewer-observed black point luminance". Presumably the 0.2cd/m^2 includes both actual veiling glare (which has many different sources - https://en.wikipedia.org/wiki/Glare_%28vision%29), and also the actual luminance of the screen when the RGB values (0,0,0) are sent to the screen. How many monitors are built, calibrated, and used in viewing conditions such that the veiling glare really is 0.2 cd/m^2? This isn't some constant of nature, it's just an assumed value that is no doubt reasonably close for some monitors and viewing conditions, but not for other monitors and viewing conditions.

My conclusion from all this is that for purposes of writing a document that is useful to programmers, the information in https://www.w3.org/Graphics/Color/srgb.pdf (sRGB specs reinterpreted) is not very useful. Programmers would first need to understand straightforward V2 ICC profiles, plus understand the changes between V2 and V4 profiles, before they could begin to decipher the contents of https://www.w3.org/Graphics/Color/srgb.pdf. And again, I'm not sure what the intended use case for the described version of the sRGB profile might be - does anyone know or have any guesses?

**Comment by peteroupc** [comment]
Just as you responded, I found out the probable real source of the document, which is the ICC itself:

http://www.color.org/chardata/rgb/srgb.xalter (section "HINTS FOR PROFILE MAKERS")

**Comment by ellelstone** [comment]
Do you have an actual link to something on the color.org website that has the "6. Tristimulus value normalization" equations?

http://www.color.org/chardata/rgb/srgb.xalter HINTS FOR PROFILE MAKERS has a link to http://www.color.org/chardata/rgb/sRGB.pdf, but that link seems to be dead.

HINTS FOR PROFILE MAKERS also has a link to http://www.color.org/chardata/rgb/icctransform.xalter, which mentions flare and black point, but doesn't have any actual equations - there is a reference to "'Correction to RGB values for non-zero black' in the ICC Extensions section", which sounds promising, but again there is no link and no such section in the V4 spec (http://www.color.org/specification/ICC1v43_2010-12.pdf).

**Comment by peteroupc** [comment]
The document in question truly _is_ at http://www.color.org/chardata/rgb/sRGB.pdf .  You may have to right-click the link and choose "Save Link As..." or "Save Target As..." to save the document, or to try again later.

In case you somehow still can't access that link, I will say that document has identical content (as far as I can tell) to the one I linked to at w3.org.
	
Also, the matter on black points was [well clarified to me](https://lists.w3.org/Archives/Public/public-colorweb/2017Sep/) by Phil Green, so that you need not respond to that issue (but can still do so if you want).  You and anyone else are still free, however, to review the rest of my article and comment on any other issues it may have.

**Comment by ellelstone** [comment]
On 09/03/2017 02:22 PM, Peter Occil wrote:
> The document in question truly _is_ at http://www.color.org/chardata/rgb/sRGB.pdf .  You may have to right-click the link and choose "Save Link As..." or "Save Target As..." to save the document, or to try again later.
> 

Ah, this time the link worked. It's the same document. There is no 
context provided for *when* someone might want to use sRGB "interpreted" 
as described in the pdf. But the logical conclusion seems to be that 
it's meant to be used as a monitor profile.

Again, in an ICC profile color-managed workflow, you don't want to use 
as your RGB *working* space profile an RGB profile with a non-zero black 
point (where R=G=B=0 doesn't point to X=Y=Z=0), because such a profile 
is not well-behaved and not suited for actual image editing. Nor does a 
specified absolute white point make any sense in the context of image 
editing using an RGB working space profile.

As far as "8" in the "interpreted" version of sRGB goes, in an image 
editing program where floating point values run from 0.0 to 1.0, the 
following equations are the only sRGB TRC equations that matter (taken 
from babl/babl/base/util.h, also see 
http://brucelindbloom.com/index.html?Eqn_XYZ_to_RGB.html and 
http://brucelindbloom.com/index.html?Eqn_RGB_to_XYZ.html, paying 
attention to the lines for the sRGB companding curve). These equations 
are for converting back and forth between linear and regular sRGB:

static inline double
linear_to_gamma_2_2 (double value)
{
   if (value > 0.003130804954)
     return 1.055 * pow (value, (1.0/2.4)) - 0.055;
   return 12.92 * value;
}

static inline double
gamma_2_2_to_linear (double value)
{
   if (value > 0.04045)
     return pow ((value + 0.055) / 1.055, 2.4);
   return value / 12.92;
}

That other stuff in the linked-to "How to interpret the sRGB color 
space", for "normalizing" from a non-zero black point - this stuff 
simply isn't relevant to what happens when editing an image in the sRGB 
ICC profile working color space. It's also not relevant for editing 
directly in the sRGB color space using for example Blender and OCIO.

Best of luck in finding whatever answers you might be looking for!

**Comment by peteroupc** [comment]
Thanks for your response.  In case you missed it, the matter on black points was [well clarified to me](https://lists.w3.org/Archives/Public/public-colorweb/2017Sep/) by Phil Green, so that you need not respond further to that issue. You and anyone else are still free, however, to review the rest of my article and comment on any other issues it may have.

**Comment by peteroupc** [comment]
@KelSolaar : Have you finished your review of this article?

**Comment by thomasmansencal** [comment]
Just re-doing another diagonal pass, I will unfortunately don't have time to do a deep review.

---

> are those of the sRGB standard of the International Electrotechnical Commission;

I would probably use the official standard reference here (and make a note that it is the **official** one): **IEC 61966-2-1:1999**

---

> to nonlinearized sRGB, where an XYZ color with Y = 1 is the D50 white point.

I would add a bold note about Chromatic Adaptation around here, .i.e. at the CIE XYZ level, it is critical for people to understand it is an essential mechanism of colour science.

---

> Y′, or luma, specifies the brightness of the color,

I would add a super bold note regarding the fact that this quantity represents non-linear luminance/gamma encoded luminance. This is important because the following: 

> the generally greater sensitivity in brightness (Y)

is  incorrect, **brightness** is a visual perception, it is a non-linear quantity akin to **lightness**. Here is **brightness** definition for reference: 

> attribute of a visual perception according to which an area appears to emit, or reflect, more or less light.

Your sentence should be _the generally greater sensitivity in luminance (Y)_, **luminance (Y)** is a linear quantity.

---

As an important side note, _lightness_, _value_, _brightness_ in the HSL, HSV and HSB models are not proper perceptual  **lightness**, **value** and **brightness** like in the CIE Lab, Munsell Renotation System and the various Colour Appearance Models.

Here is [something](https://github.com/colour-science/colour/blob/develop/colour/models/rgb/deprecated.py#L18) we have in the codebase in their regard:

```
These colour models are stated as deprecated because they trade off perceptual
relevance for computation speed. They should not be used in the colour science
domain although they are useful for image analysis and provide end user
software colour selection tools.

They are provided for convenience and completeness.

Warning
-------
Don't use that! Seriously...
```

:)

**Comment by thomasmansencal** [comment]
In regard to Luminance vs luma: http://poynton.ca/PDFs/YUV_and_luminance_harmful.pdf

**Comment by peteroupc** [comment]
I will say "the generally greater sensitivity in lightness (approximated by Y&prime;)
than in hue (approximated by Cb and Cr)".  Is this appropriate?

**Comment by peteroupc** [comment]
@KelSolaar : Do you find any of the following changes acceptable?

- "... the generally greater sensitivity in luminance (approximated by Y&prime;) than in hue in human vision"
- "... the generally greater sensitivity in lightness (approximated by Y&prime;) than in hue in human vision"
- "... the generally greater sensitivity in brightness (approximated by Y&prime;) than in hue in human vision"

I meant to say "Y&prime;" rather than "Y" here.  Do you find "...than in hue (which Cb and Cr encode in part) ..." acceptable?

**Comment by thomasmansencal** [comment]
maybe something along those lines: "such encodings take advantage of human vision greater sensitivity to spatial changes in luminance and its associated perceptual quantity Luma (Y') than spatial changes in chroma differences."

**Comment by peteroupc** [comment]
I have made many updates to this article in the meantime since September.  I would like anyone to review it.

**Comment by peteroupc** [comment]
Even now I have made many updates to [this article](https://peteroupc.github.io/colorgen.html) in the meantime over the last few months. I would like anyone to review it.  It now contains a section called "Overview of Color Vision".   See the [commits page](https://github.com/peteroupc/peteroupc.github.io/commits/master/colorgen.md) to learn what changed.

**Comment by peteroupc** [comment]
Moved to #6.
