### ISSUE TITLE
Review new pseudocode for random floating-point numbers in an arbitrary range

### ISSUE THREAD

**Issue by peteroupc** [peteroupc/peteroupc.github.io#9]
I have updated the [Uniform Random Real Numbers](https://github.com/peteroupc/peteroupc.github.io/blob/master/randomfunc.md#uniform-random-real-numbers) section of my page, "Random Number Generation and Sampling Methods", to include new pseudocode for a [method](https://github.com/peteroupc/peteroupc.github.io/blob/master/randomfunc.md#for-floating-point-number-formats) to generate random floating-point numbers in an arbitrary range.  This time, however, the method&mdash;

- covers all representable numbers in the range,
- avoids generating intermediate random floating-point numbers, and
- is generalizable to floating-point numbers of any (fixed) precision and non-binary floating-point numbers.

This is thanks to work by Downey in 2007 and @christoph-conrads with the Rademacher Floating-Point Library.

Please review this method to see if I have specified the method correctly, and report any errors you find in this issue thread.

**Comment by christoph-conrads** [comment]
> * RNDRANGE: Interval [a, b].

>   if lo<0 and hi>0

You need to check the signbit because your interval might be `[-0, +0]`: `if signbit(lo) == 1` and `signbit(hi) == 0`.

>        if ret==0 and neg==0: continue

From the code below I gather you want to implement round-toward-zero semantics (like in Rademacher FPL). Then this line must be removed because with rounding toward zero, -0 and +0 must be treated as different numbers.

Think of it this way: every floating-point number `x` in `[a,b]` has a _weight_ `w(x)` and the probability of `x` is `w(x)` divided by the sum of all weights. With round-toward zero semantics and with `signbit(x) == 0`, the weight is the distance from `x` to the next larger floating-point number `y = nextafter(x, +∞)`. With `signbit(x) == 1`, you can exploit symmetry and take the next smaller floating-point number which will be `-y`. With this method, the sum of weights will equal `b-a` but then `-0` and `+0` must be treated as different numbers.

>        if ret>=lo and ret<hi: return ret

You seem to return values from a half-open interval here but the documentation above promises values from a closed interval.

> ```
>  if v==0: ex-=1
>  break
> ```

I assume this is meant to be read as `if v == 0 then ex -= 1; else break; endif` (Downey's exponent drawing).

> ```
>    if ex==MINEXPONENT
>      s=RNDINTEXC(pow(FPRADIX,FPPRECISION))
>    else
>      sm=pow(FPRADIX,FPPRECISION-1)
>      s=RNDINTEXC(sm)+sm
> ```

Base-2 Floating-point numbers have for every exponent the same number of significand digits but for normal floats (_normal_ in contrast to a _denormal_ float) we know the represented number is not zero so during calculations we pretend the most significand bit equals one but this bit is never stored. Consequently...

> FPPRECISION is the number of significant digits in the floating-point format. Equals 53 for binary64, or 24 for binary32.

you only have to draw from 52 significand bits for binary64 and 23 significand bits for binary32, irrespective of the choice of exponent.

**Comment by peteroupc** [comment]
The sample code for RNDRANGE really is intended to produce numbers in the interval [a, b], closed in both ends.  This is done to ease the definition of the other seven methods in the RNDRANGE and RNDU01 families, given in my article.

**Comment by peteroupc** [comment]
Thank you for your review.

> 
> Base-2 Floating-point numbers have for every exponent the same number of significand digits but for normal floats (_normal_ in contrast to a _denormal_ float) we know the represented number is not zero so during calculations we pretend the most significand bit equals one but this bit is never stored. Consequently...
> 
> > FPPRECISION is the number of significant digits in the floating-point format. Equals 53 for binary64, or 24 for binary32.
> 
> you only have to draw from 52 significand bits for binary64 and 23 significand bits for binary32, irrespective of the choice of exponent.

This method is intended to apply to floating-point formats without an implied high digit (such as decimal64 and decimal128) just as well as to formats with an implied high digit (such as binary64 and binary32).  Alternatively, I could clarify that FPPRECISION includes implied (unstored) bits in the significand.

Also, note that a floating-point number with exponent of `MINEXP` can be either normal or subnormal depending on whether its digit count is either FPPRECISION or less, whereas a floating-point number with a greater exponent is always normal and always has FPPRECISION digits (in the case of normal binary floating-point numbers, the highest digit is always 1 because it's the only nonzero digit, and as a result the highest digit is often implied in binary floating-point number formats).

**Comment by peteroupc** [comment]
Section was updated.

**Comment by peteroupc** [comment]
Closed because I no longer need a review on the pseudocode.  Comments on my Randomization and Sampling Methods article are still welcome, though.
